export const CASE_TYPE_OPTIONS = {
	민사: [
		{ code: "002", name: "가합", description: "민사1심합의사건" },
		{ code: "001", name: "가단", description: "민사1심단독사건" },
		{ code: "003", name: "가소", description: "민사소액사건" },
		{ code: "004", name: "나", description: "민사항소사건" },
		{ code: "005", name: "다", description: "민사상고사건" },
		{ code: "007", name: "라", description: "민사항고사건" },
		{ code: "009", name: "마", description: "민사재항고사건" },
		{ code: "048", name: "그", description: "민사특별항고사건" },
		{ code: "010", name: "바", description: "민사준항고사건" },
		{ code: "021", name: "머", description: "민사조정사건" },
		{ code: "011", name: "자", description: "화해사건" },
		{ code: "012", name: "차", description: "독촉사건" },
		{ code: "113", name: "차전", description: "독촉사건" },
		{ code: "020", name: "러", description: "민사공조사건" },
		{ code: "051", name: "재가합", description: "민사1심합의사건재심" },
		{ code: "050", name: "재가단", description: "민사1심단독사건재심" },
		{ code: "052", name: "재가소", description: "민사소액사건재심" },
		{ code: "053", name: "재나", description: "민사항소사건재심" },
		{ code: "054", name: "재다", description: "민사상고사건재심" },
		{ code: "168", name: "재라", description: "민사항고사건재심" },
		{ code: "123", name: "재마", description: "민사재항고사건재심" },
		{ code: "124", name: "재그", description: "민사특별항고사건재심" },
		{ code: "064", name: "재머", description: "민사조정사건재심" },
		{ code: "134", name: "재자", description: "화해사건재심" },
		{ code: "058", name: "재차", description: "독촉사건재심" },
		{ code: "067", name: "준재가합", description: "민사1심합의사건준재심" },
		{ code: "066", name: "준재가단", description: "민사1심단독사건준재심" },
		{ code: "068", name: "준재가소", description: "민사소액사건준재심" },
		{ code: "105", name: "준재나", description: "민사항소사건준재심" },
		{ code: "170", name: "준재다", description: "민사상고사건준재심" },
		{ code: "174", name: "준재라", description: "민사항고사건준재심" },
		{ code: "125", name: "준재자", description: "화해사건준재심" },
		{ code: "106", name: "준재머", description: "민사조정사건준재심" },
	],
	형사: [
		{ code: "075", name: "고합", description: "형사1심합의사건" },
		{ code: "077", name: "고단", description: "형사1심단독사건" },
		{ code: "230", name: "고정", description: "약식정재청구1심단독사건" },
		{ code: "078", name: "고약", description: "약식사건" },
		{ code: "079", name: "노", description: "형사항소사건" },
		{ code: "081", name: "도", description: "형사상고사건" },
		{ code: "083", name: "로", description: "형사항고사건" },
		{ code: "085", name: "모", description: "형사재항고사건" },
		{ code: "088", name: "오", description: "비상상고사건" },
		{ code: "087", name: "보", description: "형사준항고사건" },
		{ code: "093", name: "코", description: "형사보상청구사건" },
		{ code: "090", name: "조", description: "즉결심판사건" },
		{ code: "094", name: "토", description: "형사공조사건" },
		{ code: "091", name: "초", description: "형사신청사건" },
		{ code: "204", name: "초적", description: "체포,구속적부심사건" },
		{ code: "205", name: "초보", description: "보석사건" },
		{ code: "206", name: "초기", description: "기타형사신청사건" },
		{ code: "076", name: "감고", description: "치료감호1심사건" },
		{ code: "080", name: "감노", description: "치료감호항소사건" },
		{ code: "082", name: "감도", description: "치료감호상고사건" },
		{ code: "084", name: "감로", description: "치료감호항고사건" },
		{ code: "086", name: "감모", description: "치료감호재항고사건" },
		{ code: "089", name: "감오", description: "치료감호비상상고사건" },
		{ code: "095", name: "감토", description: "치료감호공조사건" },
		{ code: "092", name: "감초", description: "치료감호신청사건" },
		{ code: "112", name: "재고합", description: "형사1심합의사건재심" },
		{ code: "113", name: "재고단", description: "형사1심단독사건재심" },
		{
			code: "231",
			name: "재고정",
			description: "약식정재청구1심단독사건(재심)",
		},
		{ code: "114", name: "재고약", description: "약식사건재심" },
		{ code: "115", name: "재노", description: "형사항소사건재심" },
		{ code: "116", name: "재도", description: "형사상고사건재심" },
		{ code: "117", name: "재감고", description: "치료감호1심사건재심" },
		{ code: "118", name: "재감노", description: "치료감호항소사건재심" },
		{ code: "119", name: "재감도", description: "치료감호상고사건재심" },
		{ code: "234", name: "고약전", description: "전자약식사건" },
		{
			code: "235",
			name: "초사",
			description: "사회봉사허가청구사건/사회봉사허가취소청구사건",
		},
		{ code: "360", name: "치고", description: "치료명령1심사건" },
		{ code: "361", name: "치노", description: "치료명령항소사건" },
		{ code: "362", name: "치도", description: "치료명령상고사건" },
		{ code: "363", name: "치오", description: "치료명령비상상고사건" },
		{
			code: "364",
			name: "치초",
			description: "치료명령신청(치료기간연장, 준수사항추가·변경·삭제청구)사건",
		},
		{ code: "365", name: "초치", description: "성폭력수형자치료명령1심사건" },
		{ code: "366", name: "치로", description: "치료명령항고사건" },
		{ code: "367", name: "치모", description: "치료명령재항고사건" },
		{
			code: "422",
			name: "초재",
			description: "재정신청사건/재정신청 비용지급신청사건",
		},
		{ code: "265", name: "전고", description: "부착명령청구1심사건" },
		{ code: "266", name: "전노", description: "부착명령청구사건 항소" },
		{ code: "267", name: "전도", description: "부착명령청구사건 상고" },
		{ code: "268", name: "전오", description: "부착명령청구사건 비상상고" },
		{ code: "269", name: "전초", description: "부착명령신청사건" },
		{ code: "264", name: "전로", description: "부착명령항고사건" },
		{ code: "270", name: "전모", description: "부착명령재항고사건" },
		{ code: "380", name: "보고", description: "보호관찰명령1심사건" },
		{ code: "381", name: "보노", description: "보호관찰명령항소사건" },
		{ code: "382", name: "보도", description: "보호관찰명령상고사건" },
		{ code: "383", name: "보오", description: "보호관찰명령비상상고사건" },
		{ code: "384", name: "보초", description: "보호관찰명령신청사건" },
		{ code: "385", name: "보로", description: "보호관찰명령항고사건" },
		{ code: "386", name: "보모", description: "보호관찰명령재항고사건" },
	],
	집행: [
		{ code: "120", name: "타", description: "집행사건" },
		{ code: "013", name: "타경", description: "부동산등경매사건" },
		{ code: "200", name: "타채", description: "채권등집행사건" },
		{ code: "014", name: "타기", description: "기타집행사건" },
		{ code: "122", name: "재타경", description: "부동산등경매사건재심" },
		{ code: "224", name: "재타기", description: "기타집행사건재심" },
		{ code: "185", name: "준재타경", description: "부동산등경매사건준재심" },
		{ code: "601", name: "본", description: "동산경매, 부동산인도명도철거 등" },
		{
			code: "602",
			name: "가",
			description: "동산가압류, 동산가처분, 부동산가처분",
		},
		{ code: "603", name: "징", description: "징수" },
		{ code: "300", name: "타인", description: "부동산인도명령사건" },
		{ code: "301", name: "타배", description: "채권배당사건" },
	],
	파산: [
		{ code: "017", name: "하", description: "파산사건" },
		{ code: "209", name: "하합", description: "파산합의사건" },
		{ code: "210", name: "하단", description: "파산단독사건" },
		{ code: "295", name: "하확", description: "파산채권조사확정사건" },
		{ code: "214", name: "하면", description: "면책사건" },
		{ code: "296", name: "하기", description: "기타파산ㆍ면책관련신청사건" },
		{ code: "256", name: "하보", description: "파산보전처분사건" },
	],
	회생: [
		{ code: "292", name: "회합", description: "회생합의사건" },
		{ code: "291", name: "회단", description: "회생단독사건" },
		{
			code: "293",
			name: "회확",
			description: "회생채권ㆍ회생담보권조사확정사건",
		},
		{ code: "294", name: "회기", description: "기타회생관련신청사건" },
		{ code: "253", name: "개회", description: "개인회생사건" },
		{ code: "254", name: "개확", description: "개인회생채권조사확정사건" },
		{ code: "290", name: "개기", description: "기타개인회생관련신청사건" },
		{ code: "255", name: "개보", description: "개인회생보전처분사건" },
	],

	비송: [
		{ code: "215", name: "비합", description: "비송합의사건" },
		{ code: "216", name: "비단", description: "비송단독사건" },
		{ code: "015", name: "파", description: "비송사건" },
		{ code: "207", name: "파합", description: "비송합의사건" },
		{ code: "208", name: "파단", description: "비송단독사건" },
		{ code: "297", name: "국승", description: "국제도산승인사건" },
		{ code: "298", name: "국지", description: "국제도산지원사건" },
		{ code: "179", name: "과", description: "과태료사건" },
		{ code: "180", name: "회", description: "회사정리사건" },
		{ code: "258", name: "회보", description: "회사정리보전처분사건" },
		{ code: "203", name: "책", description: "선박,유류등책임제한사건" },
		{ code: "181", name: "선", description: "선박소유자등의책임제한사건" },
		{ code: "182", name: "유", description: "유류오염손해배상책임제한사건" },
		{ code: "271", name: "재비합", description: "비송합의사건재심" },
		{ code: "272", name: "재비단", description: "비송단독사건재심" },
		{ code: "175", name: "재하", description: "파산사건재심" },
		{ code: "218", name: "재과", description: "과태료사건재심" },
		{ code: "176", name: "준재하", description: "파산사건준재심" },
		{ code: "223", name: "준재과", description: "과태료사건준재심" },
		{ code: "018", name: "거", description: "도산화의사건" },
		{ code: "202", name: "화", description: "도산화의사건" },
		{ code: "257", name: "화보", description: "도산화의보전처분사건" },
		{ code: "302", name: "간회단", description: "간이회생단독사건" },
		{ code: "303", name: "간회합", description: "간이회생합의사건" },
	],
	가사: [
		{ code: "160", name: "준재너단", description: "조정 단독 사건 준재심" },
		{ code: "161", name: "준재너합", description: "조정 합의 사건 준재심" },
		{ code: "023", name: "드", description: "가사1심사건" },
		{ code: "151", name: "드합", description: "가사1심합의사건" },
		{ code: "150", name: "드단", description: "가사1심단독사건" },
		{ code: "024", name: "르", description: "가사항소사건" },
		{ code: "025", name: "므", description: "가사상고사건" },
		{ code: "026", name: "브", description: "가사항고사건" },
		{ code: "027", name: "스", description: "가사재항고사건" },
		{ code: "110", name: "으", description: "가사특별항고사건" },
		{ code: "029", name: "너", description: "가사조정사건" },
		{ code: "030", name: "츠", description: "가사공조사건" },
		{ code: "028", name: "즈", description: "가사가압류,가처분등사건" },
		{ code: "178", name: "즈합", description: "가사가압류,가처분등합의사건" },
		{ code: "177", name: "즈단", description: "가사가압류,가처분등단독사건" },
		{ code: "211", name: "즈기", description: "기타가사신청사건" },
		{ code: "022", name: "느", description: "가사비송사건" },
		{ code: "163", name: "느합", description: "가사비송합의사건" },
		{ code: "162", name: "느단", description: "가사비송단독사건" },
		{ code: "461", name: "후개", description: "후견개시사건" },
		{ code: "462", name: "후감", description: "후견감독사건" },
		{ code: "463", name: "후기", description: "기타후견사건" },
		{ code: "059", name: "재드", description: "가사1심사건재심" },
		{ code: "153", name: "재드합", description: "가사1심합의사건재심" },
		{ code: "152", name: "재드단", description: "가사1심단독사건재심" },
		{ code: "060", name: "재르", description: "가사항소사건재심" },
		{ code: "061", name: "재므", description: "가사상고사건재심" },
		{ code: "146", name: "재브", description: "가사항고사건재심" },
		{ code: "147", name: "재스", description: "가사재항고사건재심" },
		{ code: "183", name: "재너", description: "가사조정사건재심" },
		{
			code: "226",
			name: "재즈합",
			description: "가사가압류,가처분등합의사건재심",
		},
		{
			code: "225",
			name: "재즈단",
			description: "가사가압류,가처분등단독사건재심",
		},
		{ code: "251", name: "재즈기", description: "기타가사신청사건재심" },
		{ code: "165", name: "재느합", description: "가사비송합의사건재심" },
		{ code: "164", name: "재느단", description: "가사비송단독사건재심" },
		{ code: "143", name: "준재드", description: "가사1심사건준재심" },
		{ code: "155", name: "준재드합", description: "가사1심합의사건준재심" },
		{ code: "154", name: "준재드단", description: "가사1심단독사건준재심" },
		{ code: "144", name: "준재르", description: "가사항소사건준재심" },
		{ code: "145", name: "준재므", description: "가사상고사건준재심" },
		{ code: "148", name: "준재브", description: "가사항고사건준재심" },
		{ code: "149", name: "준재스", description: "가사재항고사건준재심" },
		{ code: "252", name: "준재즈기", description: "기타가사신청사건준재심" },
		{ code: "167", name: "준재느합", description: "가사비송합의사건준재심" },
		{ code: "166", name: "준재느단", description: "가사비송단독사건준재심" },
		{ code: "310", name: "재으", description: "가사특별항고사건" },
	],
};
